### ISSUE TITLE
is WebApps with Docker Flow Proxy still good?

### ISSUE THREAD

**Issue by ManoMarks** [play-with-docker/play-with-docker.github.io#133]
Hey @allamand, we're doing a periodic audit of content on training.play-with-docker.com. This lab:
https://training.play-with-docker.com/docker-flow-proxy/

I've gone through it and have a few questions:

The final step of the lab doesn't seem to work, running the visualizer, do you get the same result?

Is this still a good lab for us to have in the Community section?

You use a voting app repo that comes from your account, do you think you could use the one from the `dockersamples` org instead?

@vfarcic cc'd because it's his original Flow Proxy

**Comment by allamand** [comment]
Hi @ManoMarks, sorry for the late reply.

The lab is still ok I think. I just test the final section, and you need to wait a little before the visualizer can come up but it works.
The voting app is on my personal github because I set specific labels in the yaml file

I think this lab could still be useful.

**Comment by marcosnils** [comment]
Awesome!.
