### ISSUE TITLE
docker node update - No such node: node2

### ISSUE THREAD

**Issue by darius-v** [play-with-docker/play-with-docker.github.io#92]
From this - http://training.play-with-docker.com/swarm-mode-intro/

> Updating nodes
> You can also drain a particular node, that is remove all services from that node. The services will automatically be rescheduled on other nodes.
> 
> docker node update --availability drain node2

I am getting error:

`Error: No such node: node2`

Plus for this tutorial it could be explained what service is, how it is diferent from container, what node is. Of course we can search ourselves in other resources, but this is begginers tutorial, it would be easier.

And trying to search 'docker node' - google gives pages about node.js which I assume is not the right thing.

**Comment by marcosnils** [comment]
This is probably because you missed the step at the very beginning that says `Copy the join command (watch out for newlines) output and paste it in the other terminal.`. 

After that, if you do a `docker node ls` you should see that your cluster has two nodes like this:


![image](https://user-images.githubusercontent.com/1578458/34445292-8d839022-ecb1-11e7-8d21-bd2ad80058be.png)


I'll close this as it works as expected.
