### ISSUE TITLE
Parts 2 & 3 Terminal

### ISSUE THREAD

**Issue by jonathandgall** [play-with-docker/play-with-docker.github.io#95]
Hello, At the following page: http://training.play-with-docker.com/linux-registry-part2/ the embedded terminal is not used as much, if ever.  It didn't seem to be clear from the text as I instinctively clicked on the first code excerpt as it was the pattern for the previous tutorials, to receive the error `bash: openssl: command not found`. 

Do you think it would be a bad idea to add a sentence in the introduction text precising that?

**Comment by spara** [comment]
@odajay Adding a sentence to say that this should be done on a local terminal instead of on PWD Docker is a good idea. Also, removing the '.term1' tag after the beginning of the code block would prevent the command from being copied to the terminal. We would happy to receive and merge a pull request fixing this issue.

**Comment by BretFisher** [comment]
I would think it's expected to do this inside the PWD terminal. Many won't have openssl on their local system, and doing it in PWD would save the copy/paste later.  Can we just have openssl added to the default PWD image like it was before (that tutorial used to work I think)?

**Comment by marcosnils** [comment]
@BretFisher it makes sense to do that. I'll add it and close this issue.

**Comment by marcosnils** [comment]
Fixed!.
